services:
  - type: web
    name: girlfriend-app-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://carlosbavon46:flo.kaane.74@cluster0.xyl8iot.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: EMAIL_USER
        value: your-email@gmail.com
      - key: EMAIL_PASS
        value: your-app-password
      - key: YOUR_EMAIL
        value: recipient@gmail.com

  - type: web
    name: girlfriend-app-frontend
    runtime: node
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://girlfriend-app-backend.onrender.com