services:
  - type: web
    name: girlfriend-app-backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://username:password@cluster0.syiot.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: EMAIL_USER
        value: your-email@gmail.com
      - key: EMAIL_PASS
        value: your-app-password
      - key: YOUR_EMAIL
        value: recipient@gmail.com

  - type: web
    name: girlfriend-app-frontend
    runtime: node
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://girlfriend-app-backend.onrender.com